development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: redis://redistogo:6357f0a531a23aa6749ee8f0fdc97162@pike.redistogo.com:11421/
  channel_prefix: message_me_production
